name: 100 days of code
title: Hendrik's 100 days of code challenge
description: >
    - tracking progress
about: >
    At this page I track my progress and my learnings from my 100 days of code challenge.

url: "https://hputzek.github.io/100-days-of-code"
baseurl: "/"
markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate,  jekyll-gist]

paginate: 20

logo:             assets/logo.png
disqus_shortname:

owner:
  name:           Hendrik Putzek
  avatar:         "/assets/hendrik-putzek-foto.jpg"
  email:          "hendrik.putzek@dkd.de"
  # Social networking links used in footer. Update and remove as you like.
  twitter: "hputzek"
  github: "hputzek"
  stackexchange:
  # For Google Authorship https://plus.google.com/authorship
  google_plus: "+HendrikPutzek"

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify: iQY6Mb1ycKX1SWYCSaRHhehoFf-YqZqlotlMxkg7PDM
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
